### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ReblochonMasque** [ddorn/GUI#2]
Could you please add a licence for your work, (Maybe MIT), so its possible use is well defined.
Thank you.

**Comment by ReblochonMasque** [comment]
I actually created one, and opened a pull request

**Comment by ddorn** [comment]
I think MIT is the right one. 

I've merged so I'm closing this issue. Thanks! 😃

**Comment by ReblochonMasque** [comment]
Good decision, thank you!
